#!/usr/bin/env bash

if [[ ':ux' == "$1" ]]; then                        # invoked inside tmux to take user input
	exec 3>"$2"
	shift 2
	whiptail "$@" 2>&3
	STATUS="$?"
	echo >&3
	echo "$STATUS" >&3
	exit
fi

if [[ "$1" =~ ^Allow\ use\ of\ key ]]; then         # confirm key usage
	[[ "$SSH_ASKPASS_TMUX_CHECK" ]] && "$SSH_ASKPASS_TMUX_CHECK" &>/dev/null && exit 0 # local check confirms key usage
	UX=( --yesno "$1" 10 0 --defaultno )
else                                                # ask for key passphrase
	UX=( --passwordbox "$1" 10 0 )
fi

[[ "$TMUX" ]] || exit 101
FIFO="$(mktemp --dry-run)"
function cleanup { rm -f "$FIFO"; }
trap cleanup EXIT
mkfifo -m 0600 "$FIFO" || exit 102
tmux new-window -n '+++ SSH ASK PASS +++' "$0" :ux "$FIFO" "${UX[@]}"
mapfile -n 2 -t < "$FIFO"
[[ "${MAPFILE[0]}" ]] && echo "${MAPFILE[0]}"
exit "${MAPFILE[1]}"
